controller_frequency: 20

TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 2.5 #1.5
  min_vel_theta: -1.0 #1.5

  min_in_place_vel_theta: 0.4

  #max_rotational_vel: 2.0

  acc_lim_theta: 2.5
  acc_lim_x: 1.0
  acc_lim_y: 1.0

  sim_time: 1.0

  vx_samples: 5.0
  vtheta_samples: 30.0

  pdist_scale: 0.6 #0.6
  gdist_scale: 0.8 #0.8
  occdist_scale: 0.02

  holonomic_robot: false


  meter_scoring: true # get rid of warning
